### ISSUE TITLE
This is fine: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Gawz** [currency-cop/currency-cop#97]
Receiving the error in the title on startup when the program is loading up

**Comment by ghost** [comment]
I am also seeing this message intermittently when attempting to use currency-cop.  Log data from %appdata%/Roaming/currency-cop/logs attached.

Actual IP address removed and 169.254.254.1 used in it's place.

Thanks!

`[20:08:25] [INFO] [Config] Loading file from: C:\Users\acusf\AppData\Roaming\currency-cop\Settings.db
[20:08:25] [INFO] [Portfolio] Loading file from: C:\Users\acusf\AppData\Roaming\currency-cop\Portfolios.db
[20:08:25] [INFO] [ApiClientCache] Loading file from: C:\Users\acusf\AppData\Roaming\currency-cop\Cache.db
[20:08:25] [INFO] [Config] Loading file from: C:\Users\acusf\AppData\Roaming\currency-cop\Settings.db
[20:08:25] [INFO] [Core] Loading Currency Cop v2.0.0-beta.14
[20:08:27] [WARN] [API] 302 status response for [https://www.pathofexile.com/login]: ""
[20:08:28] [INFO] [ApiClientCache] Loading file from: C:\Users\acusf\AppData\Roaming\currency-cop\Cache.db
[20:08:29] [INFO] [Portfolio] Loading file from: C:\Users\acusf\AppData\Roaming\currency-cop\Portfolios.db
[20:08:29] [INFO] [Config] Save file request: C:\Users\acusf\AppData\Roaming\currency-cop\Settings.db
[20:08:30] [INFO] [ApiClientCache] Save file request: C:\Users\acusf\AppData\Roaming\currency-cop\Cache.db
[20:08:30] [INFO] [Portfolio] Save file request: C:\Users\acusf\AppData\Roaming\currency-cop\Portfolios.db
[20:08:30] [WARN] [API] 403 status response for [https://api.github.com/repos/currency-cop/currency-cop/releases]: {"documentation_url":"https://developer.github.com/v3/#rate-limiting","message":"API rate limit exceeded for 169.254.254.1. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"}
[20:08:30] [ERROR] [Core] [App] Fatal exception: Cannot read property 'name' of undefined TypeError: Cannot read property 'name' of undefined
    at Et.<anonymous> (file:///C:/Users/acusf/AppData/Local/Programs/currency-cop/resources/app.asar/dist/bundle.js:18:683459)
    at J (file:///C:/Users/acusf/AppData/Local/Programs/currency-cop/resources/app.asar/dist/bundle.js:18:1165643)
    at Generator._invoke (file:///C:/Users/acusf/AppData/Local/Programs/currency-cop/resources/app.asar/dist/bundle.js:18:1166885)
    at Generator.Re.(anonymous function) [as next] (file:///C:/Users/acusf/AppData/Local/Programs/currency-cop/resources/app.asar/dist/bundle.js:18:1165835)
    at Yt (file:///C:/Users/acusf/AppData/Local/Programs/currency-cop/resources/app.asar/dist/bundle.js:18:672453)
    at file:///C:/Users/acusf/AppData/Local/Programs/currency-cop/resources/app.asar/dist/bundle.js:18:672564
    at <anonymous>
`

**Comment by tirrorex** [comment]
Same here, any idea on how we can help to debug this ?
